# Generated by Django 2.2.5 on 2020-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201108_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confimed', 'Confirmed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
